package com.vicmatskiv.mw;

import com.vicmatskiv.mw.CommonProxy;
import com.vicmatskiv.mw.items.guns.ACR2Factory;
import com.vicmatskiv.mw.items.guns.ACRFactory;
import com.vicmatskiv.mw.items.guns.AK101Factory;
import com.vicmatskiv.mw.items.guns.AK12Factory;
import com.vicmatskiv.mw.items.guns.AK12UFactory;
import com.vicmatskiv.mw.items.guns.AK47Factory;
import com.vicmatskiv.mw.items.guns.AK74Factory;
import com.vicmatskiv.mw.items.guns.AK74MFactory;
import com.vicmatskiv.mw.items.guns.AK74UFactory;
import com.vicmatskiv.mw.items.guns.AKMFactory;
import com.vicmatskiv.mw.items.guns.AKMNFactory;
import com.vicmatskiv.mw.items.guns.AN94Factory;
import com.vicmatskiv.mw.items.guns.AR15Factory;
import com.vicmatskiv.mw.items.guns.AS50Factory;
import com.vicmatskiv.mw.items.guns.ASValFactory;
import com.vicmatskiv.mw.items.guns.AUGA3Factory;
import com.vicmatskiv.mw.items.guns.AUGFactory;
import com.vicmatskiv.mw.items.guns.AWMFactory;
import com.vicmatskiv.mw.items.guns.AWPFactory;
import com.vicmatskiv.mw.items.guns.B92A1Factory;
import com.vicmatskiv.mw.items.guns.Deagle44Factory;
import com.vicmatskiv.mw.items.guns.DragonuvFactory;
import com.vicmatskiv.mw.items.guns.FNFALFactory;
import com.vicmatskiv.mw.items.guns.FNP90Factory;
import com.vicmatskiv.mw.items.guns.FamasF1Factory;
import com.vicmatskiv.mw.items.guns.FamasFactory;
import com.vicmatskiv.mw.items.guns.FamasG2Factory;
import com.vicmatskiv.mw.items.guns.G18Factory;
import com.vicmatskiv.mw.items.guns.G21Factory;
import com.vicmatskiv.mw.items.guns.G36CFactory;
import com.vicmatskiv.mw.items.guns.G36Factory;
import com.vicmatskiv.mw.items.guns.G36KVFactory;
import com.vicmatskiv.mw.items.guns.G3Factory;
import com.vicmatskiv.mw.items.guns.Glock18Factory;
import com.vicmatskiv.mw.items.guns.Glock19Factory;
import com.vicmatskiv.mw.items.guns.Glock32Factory;
import com.vicmatskiv.mw.items.guns.HK33Factory;
import com.vicmatskiv.mw.items.guns.HK33KFactory;
import com.vicmatskiv.mw.items.guns.HK416CFactory;
import com.vicmatskiv.mw.items.guns.HecateIIFactory;
import com.vicmatskiv.mw.items.guns.KSG12Factory;
import com.vicmatskiv.mw.items.guns.KrissVectorFactory;
import com.vicmatskiv.mw.items.guns.KrissVectorTacticalFactory;
import com.vicmatskiv.mw.items.guns.L115A3Factory;
import com.vicmatskiv.mw.items.guns.L96Factory;
import com.vicmatskiv.mw.items.guns.M1014Factory;
import com.vicmatskiv.mw.items.guns.M107Factory;
import com.vicmatskiv.mw.items.guns.M110Factory;
import com.vicmatskiv.mw.items.guns.M14Factory;
import com.vicmatskiv.mw.items.guns.M16A3Factory;
import com.vicmatskiv.mw.items.guns.M16A4Factory;
import com.vicmatskiv.mw.items.guns.M1911Factory;
import com.vicmatskiv.mw.items.guns.M1CarbineFactory;
import com.vicmatskiv.mw.items.guns.M1GarandFactory;
import com.vicmatskiv.mw.items.guns.M21Factory;
import com.vicmatskiv.mw.items.guns.M240Factory;
import com.vicmatskiv.mw.items.guns.M249Factory;
import com.vicmatskiv.mw.items.guns.M27Factory;
import com.vicmatskiv.mw.items.guns.M41AFactory;
import com.vicmatskiv.mw.items.guns.M4A1Factory;
import com.vicmatskiv.mw.items.guns.M4A42Factory;
import com.vicmatskiv.mw.items.guns.M4A4Factory;
import com.vicmatskiv.mw.items.guns.M4BenelliFactory;
import com.vicmatskiv.mw.items.guns.M82Factory;
import com.vicmatskiv.mw.items.guns.M8A7Factory;
import com.vicmatskiv.mw.items.guns.M93RFactory;
import com.vicmatskiv.mw.items.guns.M9Factory;
import com.vicmatskiv.mw.items.guns.M9SDFactory;
import com.vicmatskiv.mw.items.guns.MAC10Factory;
import com.vicmatskiv.mw.items.guns.MAC11Factory;
import com.vicmatskiv.mw.items.guns.MG36Factory;
import com.vicmatskiv.mw.items.guns.MP40Factory;
import com.vicmatskiv.mw.items.guns.MP5A5Factory;
import com.vicmatskiv.mw.items.guns.MP5Factory;
import com.vicmatskiv.mw.items.guns.MP5KFactory;
import com.vicmatskiv.mw.items.guns.MP5NFactory;
import com.vicmatskiv.mw.items.guns.MP5SDFactory;
import com.vicmatskiv.mw.items.guns.MP7Factory;
import com.vicmatskiv.mw.items.guns.MP9Factory;
import com.vicmatskiv.mw.items.guns.MXFactory;
import com.vicmatskiv.mw.items.guns.MagnumFactory;
import com.vicmatskiv.mw.items.guns.MakarovPMFactory;
import com.vicmatskiv.mw.items.guns.MakarovPMMFactory;
import com.vicmatskiv.mw.items.guns.MinimiFactory;
import com.vicmatskiv.mw.items.guns.MosinNagantFactory;
import com.vicmatskiv.mw.items.guns.P2000Factory;
import com.vicmatskiv.mw.items.guns.P220Factory;
import com.vicmatskiv.mw.items.guns.P225Factory;
import com.vicmatskiv.mw.items.guns.P226Factory;
import com.vicmatskiv.mw.items.guns.P30Factory;
import com.vicmatskiv.mw.items.guns.PP19Factory;
import com.vicmatskiv.mw.items.guns.PX90Factory;
import com.vicmatskiv.mw.items.guns.Pistol10mmFactory;
import com.vicmatskiv.mw.items.guns.PythonFactory;
import com.vicmatskiv.mw.items.guns.QBS09Factory;
import com.vicmatskiv.mw.items.guns.RPK74MFactory;
import com.vicmatskiv.mw.items.guns.Remington900Factory;
import com.vicmatskiv.mw.items.guns.SMAWFactory;
import com.vicmatskiv.mw.items.guns.SPAS12Factory;
import com.vicmatskiv.mw.items.guns.SR25Factory;
import com.vicmatskiv.mw.items.guns.SV98Factory;
import com.vicmatskiv.mw.items.guns.ScarFactory;
import com.vicmatskiv.mw.items.guns.ScarHFactory;
import com.vicmatskiv.mw.items.guns.TAR21Factory;
import com.vicmatskiv.mw.items.guns.UMP45Factory;
import com.vicmatskiv.mw.items.guns.UMP9Factory;
import com.vicmatskiv.mw.items.guns.USP45Factory;
import com.vicmatskiv.mw.items.guns.VSSVintorezFactory;
import com.vicmatskiv.mw.items.guns.XEagleFactory;
import com.vicmatskiv.mw.items.guns.XWPFactory;
import com.vicmatskiv.weaponlib.compatibility.CompatibleFmlInitializationEvent;
import com.vicmatskiv.weaponlib.config.ConfigurationManager;
import net.minecraft.item.Item;

public class Guns {
   public static Item AK47;
   public static Item AKM;
   public static Item AK12;
   public static Item AK74U;
   public static Item AK74M;
   public static Item M4A1;
   public static Item M4A4;
   public static Item M27;
   public static Item AR15;
   public static Item M16A3;
   public static Item M16A4;
   public static Item FNFAL;
   public static Item Scar;
   public static Item ScarH;
   public static Item G18;
   public static Item G21;
   public static Item M9;
   public static Item B92A1;
   public static Item USP45;
   public static Item XEagle;
   public static Item P2000;
   public static Item Magnum;
   public static Item PX90;
   public static Item G36;
   public static Item G36C;
   public static Item AUG;
   public static Item Famas;
   public static Item FamasG2;
   public static Item FamasF1;
   public static Item MP5;
   public static Item MP5K;
   public static Item MP7;
   public static Item AS50;
   public static Item M14;
   public static Item M110;
   public static Item XWP;
   public static Item Dragonuv;
   public static Item M107;
   public static Item Remington870;
   public static Item KSG12;
   public static Item M1014;
   public static Item SPAS12;
   public static Item M240;
   public static Item M249;
   public static Item RPK74M;
   public static Item MG36;
   public static Item ACR;
   public static Item HK416C;
   public static Item M1Carbine;
   public static Item MP40;
   public static Item AN94;
   public static Item M1911;
   public static Item AUGA3;
   public static Item AK74;
   public static Item MX;
   public static Item M4A42;
   public static Item M9SD;
   public static Item L96;
   public static Item AWP;
   public static Item SV98;
   public static Item L115A3;
   public static Item AWM;
   public static Item MosinNagant;
   public static Item M82;
   public static Item M21;
   public static Item HK33;
   public static Item M93R;
   public static Item Python;
   public static Item AK101;
   public static Item MakarovPM;
   public static Item MakarovPMM;
   public static Item G36KV;
   public static Item HK33K;
   public static Item KrissVector;
   public static Item KrissVectorTactical;
   public static Item P225;
   public static Item P220;
   public static Item P226;
   public static Item Glock19;
   public static Item P30;
   public static Item MP5A5;
   public static Item MP5SD;
   public static Item FNP90;
   public static Item MAC10;
   public static Item MAC11;
   public static Item MP5N;
   public static Item G3;
   public static Item AK12U;
   public static Item QBS09;
   public static Item M4Benelli;
   public static Item PP19;
   public static Item Glock32;
   public static Item SR25;
   public static Item Minimi;
   public static Item ACR2;
   public static Item Glock18;
   public static Item HecateII;
   public static Item Deagle44;
   public static Item VSSVintorez;
   public static Item ASVal;
   public static Item UMP45;
   public static Item UMP9;
   public static Item TAR21;
   public static Item MP9;
   public static Item M8A7;
   public static Item M1Garand;
   public static Item AKMN;
   public static Item SMAW;
   public static Item M41A;
   public static Item Pistol10mm;

   public static void init(Object mod, ConfigurationManager configurationManager, CompatibleFmlInitializationEvent event, CommonProxy proxy) {
      AK47 = (new AK47Factory()).createGun(proxy);
      AKM = (new AKMFactory()).createGun(proxy);
      AKMN = (new AKMNFactory()).createGun(proxy);
      AK12 = (new AK12Factory()).createGun(proxy);
      AK12U = (new AK12UFactory()).createGun(proxy);
      AN94 = (new AN94Factory()).createGun(proxy);
      AK74U = (new AK74UFactory()).createGun(proxy);
      AK74 = (new AK74Factory()).createGun(proxy);
      AK74M = (new AK74MFactory()).createGun(proxy);
      AK101 = (new AK101Factory()).createGun(proxy);
      AR15 = (new AR15Factory()).createGun(proxy);
      M4A1 = (new M4A1Factory()).createGun(proxy);
      M4A42 = (new M4A42Factory()).createGun(proxy);
      M27 = (new M27Factory()).createGun(proxy);
      M4A4 = (new M4A4Factory()).createGun(proxy);
      M16A3 = (new M16A3Factory()).createGun(proxy);
      M16A4 = (new M16A4Factory()).createGun(proxy);
      HK416C = (new HK416CFactory()).createGun(proxy);
      ACR2 = (new ACR2Factory()).createGun(proxy);
      ACR = (new ACRFactory()).createGun(proxy);
      Scar = (new ScarFactory()).createGun(proxy);
      ScarH = (new ScarHFactory()).createGun(proxy);
      MX = (new MXFactory()).createGun(proxy);
      FNFAL = (new FNFALFactory()).createGun(proxy);
      M1Carbine = (new M1CarbineFactory()).createGun(proxy);
      G18 = (new G18Factory()).createGun(proxy);
      Glock18 = (new Glock18Factory()).createGun(proxy);
      Glock19 = (new Glock19Factory()).createGun(proxy);
      G21 = (new G21Factory()).createGun(proxy);
      Glock32 = (new Glock32Factory()).createGun(proxy);
      M9 = (new M9Factory()).createGun(proxy);
      B92A1 = (new B92A1Factory()).createGun(proxy);
      M93R = (new M93RFactory()).createGun(proxy);
      M9SD = (new M9SDFactory()).createGun(proxy);
      USP45 = (new USP45Factory()).createGun(proxy);
      XEagle = (new XEagleFactory()).createGun(proxy);
      Deagle44 = (new Deagle44Factory()).createGun(proxy);
      P2000 = (new P2000Factory()).createGun(proxy);
      P30 = (new P30Factory()).createGun(proxy);
      P220 = (new P220Factory()).createGun(proxy);
      P225 = (new P225Factory()).createGun(proxy);
      P226 = (new P226Factory()).createGun(proxy);
      Magnum = (new MagnumFactory()).createGun(proxy);
      Python = (new PythonFactory()).createGun(proxy);
      M1911 = (new M1911Factory()).createGun(proxy);
      MakarovPM = (new MakarovPMFactory()).createGun(proxy);
      MakarovPMM = (new MakarovPMMFactory()).createGun(proxy);
      Remington870 = (new Remington900Factory()).createGun(proxy);
      KSG12 = (new KSG12Factory()).createGun(proxy);
      M1014 = (new M1014Factory()).createGun(proxy);
      M4Benelli = (new M4BenelliFactory()).createGun(proxy);
      SPAS12 = (new SPAS12Factory()).createGun(proxy);
      QBS09 = (new QBS09Factory()).createGun(proxy);
      G36 = (new G36Factory()).createGun(proxy);
      G36C = (new G36CFactory()).createGun(proxy);
      G36KV = (new G36KVFactory()).createGun(proxy);
      AUG = (new AUGFactory()).createGun(proxy);
      AUGA3 = (new AUGA3Factory()).createGun(proxy);
      Famas = (new FamasFactory()).createGun(proxy);
      FamasG2 = (new FamasG2Factory()).createGun(proxy);
      FamasF1 = (new FamasF1Factory()).createGun(proxy);
      HK33 = (new HK33Factory()).createGun(proxy);
      HK33K = (new HK33KFactory()).createGun(proxy);
      MP5 = (new MP5Factory()).createGun(proxy);
      MP5A5 = (new MP5A5Factory()).createGun(proxy);
      MP5N = (new MP5NFactory()).createGun(proxy);
      MP5SD = (new MP5SDFactory()).createGun(proxy);
      MP5K = (new MP5KFactory()).createGun(proxy);
      PP19 = (new PP19Factory()).createGun(proxy);
      MP7 = (new MP7Factory()).createGun(proxy);
      FNP90 = (new FNP90Factory()).createGun(proxy);
      PX90 = (new PX90Factory()).createGun(proxy);
      KrissVector = (new KrissVectorFactory()).createGun(proxy);
      KrissVectorTactical = (new KrissVectorTacticalFactory()).createGun(proxy);
      MAC10 = (new MAC10Factory()).createGun(proxy);
      MAC11 = (new MAC11Factory()).createGun(proxy);
      MP40 = (new MP40Factory()).createGun(proxy);
      AS50 = (new AS50Factory()).createGun(proxy);
      XWP = (new XWPFactory()).createGun(proxy);
      L115A3 = (new L115A3Factory()).createGun(proxy);
      L96 = (new L96Factory()).createGun(proxy);
      AWP = (new AWPFactory()).createGun(proxy);
      AWM = (new AWMFactory()).createGun(proxy);
      SV98 = (new SV98Factory()).createGun(proxy);
      HecateII = (new HecateIIFactory()).createGun(proxy);
      MosinNagant = (new MosinNagantFactory()).createGun(proxy);
      Dragonuv = (new DragonuvFactory()).createGun(proxy);
      VSSVintorez = (new VSSVintorezFactory()).createGun(proxy);
      M14 = (new M14Factory()).createGun(proxy);
      M21 = (new M21Factory()).createGun(proxy);
      M110 = (new M110Factory()).createGun(proxy);
      SR25 = (new SR25Factory()).createGun(proxy);
      G3 = (new G3Factory()).createGun(proxy);
      M82 = (new M82Factory()).createGun(proxy);
      M107 = (new M107Factory()).createGun(proxy);
      M240 = (new M240Factory()).createGun(proxy);
      M249 = (new M249Factory()).createGun(proxy);
      Minimi = (new MinimiFactory()).createGun(proxy);
      MG36 = (new MG36Factory()).createGun(proxy);
      RPK74M = (new RPK74MFactory()).createGun(proxy);
      ASVal = (new ASValFactory()).createGun(proxy);
      UMP45 = (new UMP45Factory()).createGun(proxy);
      UMP9 = (new UMP9Factory()).createGun(proxy);
      TAR21 = (new TAR21Factory()).createGun(proxy);
      MP9 = (new MP9Factory()).createGun(proxy);
      M8A7 = (new M8A7Factory()).createGun(proxy);
      M1Garand = (new M1GarandFactory()).createGun(proxy);
      M41A = (new M41AFactory()).createGun(proxy);
      Pistol10mm = (new Pistol10mmFactory()).createGun(proxy);
      SMAW = (new SMAWFactory()).createGun(proxy);
   }
}
